### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by danielpassos**
This PR is part of [RHMAP-2465](https://issues.jboss.org/browse/RHMAP-2465) and contains: 
- Cleanup app
- Bump fh-android-sdk to 2.5.0
- Bump Android Gradle Tools to 1.3.1
- Downgrade minSdkVersion to 7
- Fix lint warnings
- Start use Material design

### CODE REVIEW

**Comment by danielpassos** [comment]
@wei-lee @secondsun Could you give it a spin?

To test it, just create a hello world cloud app and update the `app/src/main/assets/fhconfig.properties` with your app credentials

**Comment by wei-lee** [comment]
:eyes:

**Comment by wei-lee** [comment]
Have built and installed the app on an Android 4.4 device. Everything works as expected.

**Comment by danielpassos** [comment]
hi 5

**Pull request merged**
