### PR TITLE
Adding in code coverage

### PR DESCRIPTION
**Pull request by secondsun**
# Adding in Code coverage reports
## Steps to test

``` bash
./gradlew clean connectedCheck 
firefox app/build/reports/coverage/debug/index.html 
```

Observe that you see a code coverage report reading 50 ish percent coverage.
## Notes

<strike>JUnitJacocoTestRunner is a class I found to work around a known bug in the test runner.  Google claims it will be fixed in test runner 0.4.  Test runner 0.4 is published, but it requires build tools 23 (and this Android M).  When Android M support is made available in Digger we can upgrade the template and remove the workaround.</strike>

Found a workaround to use the fixed libs and stay on Android 22.

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos & @wei-lee :eyes: ?

**Comment by danielpassos** [comment]
:+1:

**Comment by secondsun** [comment]
@danielpassos Rebased on master (with your travis stuff) will merge when travis passes

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
